"""Workspace folder definitions."""

from __future__ import annotations

WORKSPACE_DIRS = (
    "targets/target-notes",
    "targets/imported-target-metadata",
    "headers/imported",
    "headers/normalized",
    "headers/extracted",
    "headers/metadata",
    "jobs/drafts",
    "jobs/queued",
    "jobs/completed",
    "jobs/failed",
    "jobs/skipped",
    "jobs/command-arrays",
    "jobs/command-previews",
    "queue/autosaves",
    "queue/history",
    "hashcat/sessions",
    "hashcat/restore",
    "hashcat/potfile",
    "hashcat/logs",
    "hashcat/output",
    "inputs/keyfiles/normalized",
    "inputs/keyfiles/imported-full",
    "inputs/keyfiles/thumbnails",
    "inputs/keyfiles/manifests",
    "inputs/wordlists/imported",
    "inputs/wordlists/manifests",
    "inputs/rules/imported",
    "inputs/masks/imported",
    "generated/wordlists",
    "generated/masks",
    "generated/candidates",
    "generated/keyfile-lists",
    "generated/pim-lists",
    "generated/recipes",
    "generated/commands",
    "generated/hash-inputs",
    "temp/active-job",
    "temp/staging",
    "reports/csv",
    "reports/json",
    "reports/markdown",
    "reports/text",
    "reports/cracked",
    "reports/diagnostics",
    "logs/app",
    "logs/queue",
    "logs/errors",
    "cleanup",
)

WORKSPACE_FILES = (
    "workspace.json",
    "settings.json",
    "targets/targets.json",
    "queue/queue-state.json",
    "cleanup/cleanup-manifest.json",
)
